### PR TITLE
add cannbc, cannbl

### PR DESCRIPTION
**Pull request by rschen7754**

### CODE REVIEW

**Comment by jteresco** [comment]
Live on site.

**Comment by yakra** [comment]
cannbc is using a larger font size than cannbl, which makes the numerals bleed over the bleed over the province outline onto the background.

**Comment by rschen7754** [comment]
The cannbc seems to be browser dependent - it looks good on Firefox on Mac, but does bleed on Chrome on Linux. The font differences on the platforms are probably the cause.

I'm reluctant to change the sizes too much since the templates on Wikimedia Commons do show a difference in font sizes (https://commons.wikimedia.org/wiki/Category:Diagrams_of_New_Brunswick_route_markers).

**Comment by yakra** [comment]
Makes sense. I'm running Linux, so I would have to be using a different, free software, from Mac or Windows.

**Pull request merged**
