### PR TITLE
Bug fix plus some other things

### LINKED ISSUE #39: Wrong % value if rte parameter is used in url
http://tm.teresco.org/hbtest/mapview.php?u=terescoj&rte=I-90

For instance, 1.00% is displayed in the table instead of 100%

### PR DESCRIPTION
**Pull request by theFXexpert**
Fixes #39.

### CODE REVIEW

**Comment by theFXexpert** [comment]
Oh. I put log links commit in this pull request by accident. I kinda wanted it to be separate. Oh well.

**Comment by theFXexpert** [comment]
Added a request from #18.

**Comment by yakra** [comment]
Jim, is this something where you'd want to download this branch of the code and give it a test drive before merging it in?

**Comment by jteresco** [comment]
Yes, and I forgot about it.  I have no time right now but will try to check it out soon.

**Comment by jteresco** [comment]
Apologies for the ridiculously long delay. I'm bringing this in now and the changes will be live soon.

**Pull request merged**
