### PR TITLE
I updated the credits page since Weston County updated their website

### PR DESCRIPTION
**Pull request by the-spui-ninja**

### CODE REVIEW

**Comment by yakra** [comment]
Thoughts on whether we should retain old links for historical/completeness purposes?
ISTR some discussion of flagging dead links on the forum...
Thoughts on adding a note on when each link was accessed, as done on Wikipedia?

**Comment by jteresco** [comment]
I like to leave old ones, update links if possible, link to archive.org if possible.  "Accessed on" would be useful to add.

**Comment by jteresco** [comment]
Live on the main site.

**Comment by the-spui-ninja** [comment]
To be fair with this one, none of the data changed, they just redesigned their website and moved where the stuff was located (I used it the first time and there weren't differences)... sorry should have made that clear.

**Comment by jteresco** [comment]
OK, good.  In that case, a simple update to the new location is sufficient.

**Pull request merged**
