### PR TITLE
Improve UX when loading large datasets

### PR DESCRIPTION
**Pull request by Thing342**
This pull request separates the code that produces the waypoint JS into a separate file, so that it can be loaded asynchonously. This means that loading of map waypoints no longer blocks the loading of the rest of the page.

Affects: HB, mapview, system and region pages.

(I can pull this in myself, but I'd like to have Jim take a look at it first)

### CODE REVIEW

**Comment by jteresco** [comment]
I'll check it out soon, thanks.

**Comment by Thing342** [comment]
Note - this code is live at (http://ec2-107-20-99-209.compute-1.amazonaws.com:9999/)

**Comment by michihdeu** [comment]
Try to load this: http://ec2-107-20-99-209.compute-1.amazonaws.com:9999/user/mapview.php?rg=AUT,BEL,CHE,CZE,DEU,DNK,ESP,FRA,HUN,ITA,LUX,NOR,NLD,POL,ROU,SVN,SWE&u=michih.
The script crashes with this rg combination on tm.teresco.org too (it worked till Mid 2016 though).

**Comment by Thing342** [comment]
@michihdeu loaded fine for me on both sites, just took awhile. Are you sure it's not your browser having trouble with the massive number of waypoints?

**Comment by michihdeu** [comment]
Loading takes ages with IE11 but the script crashes with FF50.
I could load http://tm.teresco.org/user/mapview.php?rg=AUT,BEL,CHE,CZE,DEU,DNK,ESP,FRA,HUN,ITA,LUX,NLD,NOR,POL,ROU,SVN,SWE,AB,BC,ON,QC,IL,MI&u=michih with FF last summer though (+ AB,BC,ON,QC,IL,MI but w/o some new European systems in preview).

**Comment by michihdeu** [comment]
It seems to crash at different positions. Not a bug but a performance problem. I haven't reported it earlier because I hoped it might be better with the optimized data loading...

**Comment by jteresco** [comment]
This is live on tmtest but not working:


error

I can investigate but not right away.  Guessing some file either didn't get updated in the repository or I didn't copy it to the right place on tmtest.

**Comment by Thing342** [comment]
@jteresco  I'm guessing you didn't copy over /api/waypoints.js.php, which is where the way-point generation logic was moved to.

**Comment by jteresco** [comment]
That's it.  Looks to be working now.  Please check it out and if all is good, I'll install on production soon.

**Comment by Thing342** [comment]
Confirmed working. Can be safely merged

**Pull request merged**
