### PR TITLE
Keep valid HB link when label lookup fails

### LINKED ISSUE #387: datacheck.php: HB links when label lookup fails
#383 introduced some undesired behavior for MALFORMED_URL, MALFORMED_LAT and MALFORMED_LON cases, because these points [don't get added to the DB](https://github.com/TravelMapping/DataProcessing/issues/57#issuecomment-450404359).

The resulting link will be something like http://travelmapping.net/hb/?r=me.i295&lat=&lon=&zoom=17, which initializes the HB view to (0°, 0°) near the Gulf of Guinea.

### PR DESCRIPTION
**Pull request by yakra**
closes #387

### CODE REVIEW

**Review by jteresco — COMMENTED** [review]
Just on a quick look, wouldn't we want that to be when row2 is not NULL?

**Comment by yakra** [comment]
Good catch, thanks. I had it right in emacs on lab2, I swear! :D
[Looks like GitHub can cope with force pushes now](https://github.com/TravelMapping/Web/pull/623#event-4305036988); this should be good to go.

**Comment by jteresco** [comment]
Live on the main site.

**Comment by yakra** [comment]
...And broken! Forgot a semicolon both times. Fix forthcoming.

**Comment by jteresco** [comment]
Yes, I suppose I should have actually gone to the page after I installed just to make sure!

**Comment by yakra** [comment]
#626

**Comment by yakra** [comment]
Good news is...
I thought there were some bugs preventing me from running the latest Web commits on lab2, the ones I'd be branching from while working with GitKraken on my desktop. But nope, it's fine. So I can edit/stage/commit/etc. on BiggaTomato, and scp the files on over to lab2 & test, and hopefully prevent this kind of thing from happening.

**Comment by jteresco** [comment]
That's good.  Glad you noticed and fixed it quickly.

**Pull request merged**
