### PR TITLE
Typo fixes on credits page

### PR DESCRIPTION
**Pull request by ovoss**
My last update left California entries blank (commented out?), and threw off formatting of all entries after New Mexico. Hope this fixes both issues.

### CODE REVIEW

**Comment by jteresco** [comment]
I'll try it.  Sorry I didn't even try loading the page before.  I'm sure I could have made a quick fix.

**Comment by jteresco** [comment]
This one looks like it renders nicely, thanks.

**Comment by ovoss** [comment]
The California listings don't render at all, and I can't figure out why. 

Oscar 

----- Original Message -----

**Comment by jteresco** [comment]
There was an open comment tag (<!-- ) at the start.  I should have looked more closely to see if everything made it.  I fixed it.

**Pull request merged**
