### PR TITLE
Shields: Complete Crossover Bugfix + AS Template Improved

### PR DESCRIPTION
**Pull request by theFXexpert**
Complete the fix for #121
Also may help with explicitly sorting #586 a bit.

American Samoa template improved:
- Use the standard MUTCD green.
- Add white borders.
- Center the number alignment.

### CODE REVIEW

**Comment by jteresco** [comment]
This one's on tmstage, thanks.

**Comment by theFXexpert** [comment]
Seems to look fine as best as I can tell. The only issue is Manitoba Trunk and PR display the ***SYS*** placeholder in the generic template since it doesn't get replaced in that case. I made a couple quick MB templates to make it look better. I left MB for one of the last ones since Yakra said they wanted to work on it and MB uses superscripted suffixes. PR can be commented out of the case until we decide how to do shields for it. I can do another pull request if you feel that is fine.

**Comment by jteresco** [comment]
Yes, please go ahead and put in a pull request for what you'd like to see go onto the production server.

**Comment by rickmastfan67** [comment]
@theFXexpert Ontario also uses superscripted suffixes.  Both for the 'main' canon & the in progress canons systems.

**Comment by theFXexpert** [comment]
> @theFXexpert Ontario also uses superscripted suffixes. Both for the 'main' canon & the in progress canons systems.

I have been looking on streetview to reference canons and it seems a mix of styles are used for suffixes in field signage. What I have seen the most so far is the suffix is smaller but on the same baseline as the rest of the number unlike canon and canmb where suffix is raised (superscripted). I have only looked at the canons routes drafted so far. If the standard design is supposed to be superscripted, I can adjust my local template accordingly.

**Pull request merged**
