### PR TITLE
Pull Request 070716

### PR DESCRIPTION
**Pull request by Thing342**
A compilation of new fixes and features that I've been working on for the past few weeks.

Notes:
*Improved user selection navigation across the site. 
 *stat.php now shows the current user's stats and ranks at the top, if one is selected.
 *Added "back to user page" links on region.php and system.php
 *Added user selection to hb.php, as requested in #42.
*Added some statistics to highway pages, including total mileage, LIST name, number of drivers, number clinched, and average mileage per driver.
 *Also added per-segment statistics, showing the percentage of drivers who have traveled it.
*Fixes for #73 and #92, as well as implementations of #42, #48, and #93.

### CODE REVIEW

**Comment by jteresco** [comment]
Thanks for all of these.  They're live on tmtest, and I'll get them over on the main site soon unless some problems are uncovered in a little testing.

**Comment by michihdeu** [comment]
Thanks for the great improvement :+1: 

> *Added user selection to hb.php, as requested in #42.

The links from [user stats](http://tmtest.teresco.org/user/?u=michih) to HB are broken now: 
http://tmtest.teresco.org/hb/?u=michih
instead of
http://tm.teresco.org/hb?rg=DEU
but should be 
http://tmtest.teresco.org/hb?rg=DEU&rg&u=michih

**Comment by michihdeu** [comment]
> *stat.php now shows the current user's stats and ranks at the top, if one is selected.

I like that very much :+1: 

Nevertheless, I'm not sure how it works:

For instance, German A1 which I've clinched: http://tm.teresco.org/hb/index.php?u=michih&r=deu.a001.

> Total Mileage	380.63 mi
> LIST Name	DEU A1
> Average Mileage	112.77 mi (29.63 %)
> Total Drivers	12 (9.23 %)
> Total Clinched	1 (0.77 %)
> 8.33 % of drivers

Why is (my?) average milage 29.63% only?

> Waypoints
> Coordinates	Name	%

What's indicated in the % column? Values are changing?

> (54.094612,10.775914)	14	25.00
> (54.052259,10.733814)	15	16.67
> (54.034721,10.729179)	16	25.00

Is data not calculated for the selected user but for all users? (which should only be displayed if none is selected)

Why are higher % values red? I think it should be green, shouldn't it? Maybe 0-50% red to light red, 50-100% light green to green? Just my 2c...

**Comment by Thing342** [comment]
@michihdeu: 
The stats on the HB pages are not dependent on the user.

"Average Mileage" is the average distance traveled by users who have driven the road (ie, people who have driven the road have driven it on average 112.77 miles)

The percentages are the percentage of drivers who have traveled the segment that starts at that waypoint.

**Comment by michihdeu** [comment]
OK.

**Comment by rickmastfan67** [comment]
I don't know if this was to effect the 'update' page, but I can no longer go directly to a route page from it.
http://tm.teresco.org/devel/updates.php#updates
Any link to a route from that page takes me to the "Travel Mapping Highway Browser" instead.  So, if I want to double check a route from that page, I have to go to the system, then the route.  Very annoying and time consuming.

**Comment by michihdeu** [comment]
> Any link to a route from that page takes me to the "Travel Mapping Highway Browser" instead. 

It works for me. I've clicked on the first 6 links (eng.a1173imm,...), all are fine.

**Comment by rickmastfan67** [comment]
Well, still a no-go for me in both IE & FF.  Takes me to this URL everytime: http://tm.teresco.org/hb/?u=rickmastfan67

Could there be some bug with the site cookies?  It works fine when I'm in 'private' mode for FF, just not in the normal part that stores the cookies.

**Comment by michihdeu** [comment]
I don't think that it's in combination with private mode but it depends whether an user is selected. If cookies are cleared and you open the update page, no user is known and it works. If you select a user via 'Traveler Stats' first, it does not work. I think it's a duplicate to the problem I've reported that HB is not opened from user stats (because user is always known there).

**Pull request merged**
