### PR TITLE
quick-n-dirty system.php rankings table

### PR DESCRIPTION
**Pull request by yakra**

### CODE REVIEW

**Comment by yakra** [comment]
Needs more bells & whistles! :)

**Comment by yakra** [comment]
7e8762aa69baf6ec2c3880938e0af3ddc41852f8 includes:
* anchor as requested by formulanone in the forum
* rank numbers [like CHM used to have](http://web.archive.org/web/20160422033800/http://cmap.m-plex.com/stat/travsystem.php?sys=deua)

Changes are live on lab2 if you'd like to test them out. As usual, please don't publicize the IP.

**Comment by jteresco** [comment]
Thanks.  I've merged this and put it onto tmstage.teresco.org for testing.

**Comment by yakra** [comment]
:+1:

**Comment by yakra** [comment]
@FL0gnap, this is the big one I texted you about.
#653 contained some follow-up tweaks.

**Pull request merged**
