### PR TITLE
Userpages

### PR DESCRIPTION
**Pull request by Thing342**
This is what I've been working on for the past 2 weeks or so. There are definitely issues and bugs that need to be ironed out (mostly related to the shield generator), but it's mostly feature-complete. I think putting it up now for others to test will help to find any major bugs.

### CODE REVIEW

**Comment by yakra** [comment]
Thanks for all your work on this. I can't wait to take it for test drive.

**Comment by jteresco** [comment]
Yes, I am excited to see what this can do.  I'll get it up on the server tonight, I hope.  Should be able to give it a try after 9:30 EST.  Thanks.

**Comment by jteresco** [comment]
This is a big enough change that I didn't want to pull it all right in and install on the main server without some people to check it out.  So for now, I grabbed a copy of the branch and extracted it so it's available at http://tmtest.teresco.org

I like the stats!  I am not sure which of the other functionality is expected to work, so please give it a try.

**Comment by rschen7754** [comment]
The links from the stats page seem to be going to http://tmtest.teresco.org/user/user/system.php?u=rschen7754&sys=usaoh (I assume /user/user is supposed to be just /user). Same for the map pages.

**Comment by Thing342** [comment]
Not sure why that would happen when the only change is the server location (didn't come up on my local dev stack). Will have to give that as well as the various header messages a look in the morning.

**Comment by Thing342** [comment]
Latest commit should fix a few of the existing issues: https://github.com/Thing342/Web/commit/fd8580bebcb70bec6013a6d487e94dba552039d7

**Pull request merged**
