### PR TITLE
Shields: Big Update

### PR DESCRIPTION
**Pull request by theFXexpert**
New templates:
- #594 frad, fram
- #597 gbnb, nirb, irlr
- #606 canabs
- canons

Updated/Optimized templates:
- Generic wide
- canbc refined suffixes
- canmb refined suffixes
- canon refined suffixes
- canonf
- hunm, hunf (does this fix weirdness with #615 ?)

#71 Let shields auto scale to fit height.
Use strict comparison operators in shield generator.

### CODE REVIEW

**Comment by rickmastfan67** [comment]
The Ontario shields (both types) with the 'A' & 'B' in them look great now!

**Comment by michihdeu** [comment]
Thx! [frad + fram](https://github.com/TravelMapping/Web/issues/594) look good. However, the shield radius seems to be a little bit to big. Not sure whether we need a radius at all. The A, B,... suffixes are usually smaller but I think it would be hard to implement this.

**Comment by theFXexpert** [comment]
I made radius a bit bigger trying to approximate field posts, but I can reduce it to be the same as the national/autoroutes.
Small suffixes are no problem for me to do now as long as I know the case-sensitive pattern of what is a suffix. (A-Z a-z?) I'm guessing 'Bis' and 'Ter' are generally small suffixes? 
https://tmstage.teresco.org/hb/showroute.php?r=fraidf.d0023ter93 
https://tmstage.teresco.org/hb/showroute.php?r=fraidf.d0023bis93

I think I saw one with a number in the suffix but I can't remember where or what route I saw it on GMSV

**Comment by michihdeu** [comment]
Any suffix with `A-Z`, `a-z`, `bis`, `BIS`, `ter`,... should be small.
All index suffixes, e.g. [`D8.7`](https://tmstage.teresco.org/hb/showroute.php?r=fraara.d0008742) should be small that means, `.` should be omitted and the number behind should be small.

**Pull request merged**
