### PR TITLE
Manual: How to participate in the project

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco minor changes except of the last two commits.

It moves _participate.php_ from devel -> home (root directory).

If possible I'd like to test the links today. If the poll about point request on the manual will be rejected (very likely), I just need to make it visible on the home page tomorrow (by changing the "How to Participate" paragraph on the home page).

**Comment by jteresco** [comment]
This should be up now.

What's putting all those chain/link icons in?  I'd like to get rid of those.

**Comment by michihdeu** [comment]
> What's putting all those chain/link icons in? I'd like to get rid of those.

@yakra has introduced them to the manual. You can click on them to copy the link to clipboard.

I like it very much because you can directly copy the link if you have a question or if you wanna show one the solution to a problem etc.

**Comment by michihdeu** [comment]
It's the `&#x1f517` from lines like `<p class="subheading"><a name="announce"></a><a style="text-decoration:none" href="#announce">&#x1f517</a>
Announce that you will do a peer-review</p>`

**Comment by michihdeu** [comment]
> This should be up now.

No, it's not! @jteresco

**Comment by michihdeu** [comment]
It's in place now and links work.

I forgot removing "Draft" in the headline and changing the color from red to black. Locally fixed.

**Comment by jteresco** [comment]
I first installed it on tmtest by mistake (breaking scrollable mapview, temporarily)...

If the link icons serve a useful purpose, I can live with them.  Just think they're ugly and confusing!

**Comment by michihdeu** [comment]
Yes, the icons are not pretty but I'm used to them now 😃

**Pull request merged**
