### PR TITLE
data errors manual + (new) data check page error colors

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by yakra** [comment]
I'd check this out in detail but it's almost sleep o'clock. In the mor--afternoon!

**Comment by yakra** [comment]
**syserr.php**
```diff
< <li>For example, a <conn2>green line</conn1>
> <li>For example, a <conn2>green line</conn2>

The rest looks good!
```

**Comment by michihdeu** [comment]
> Also: duplicate the datacheck.php changes in the live devel/datacheck.php?

I cannot test it on my end and don't wanna break anything. But I think that there is virtually now chance to make anything wrong here....

and: I was not sure whether we should announce on the forum..... or even ask whether it is fine.... OTOH, I think that virtually no one cares............. till the day anyone is directly effected by an error report or reminder to fix errors.......

**Comment by jteresco** [comment]
Drop a note in here when you're ready to have this go live.

**Comment by yakra** [comment]
The changes are pretty straightforward, but I can merge this in & make the corresponding changes to /devel/datacheck.php, test them out on lab2 for good measure, and commit.

**Comment by michihdeu** [comment]
The latest commit closes https://github.com/TravelMapping/Web/issues/355

**Comment by yakra** [comment]
Closes #355.

(Do we have to phrase it like that in order to count as a linked issue that will be closed? Does it have to be in the OP?)

**Comment by yakra** [comment]
@michihdeu, is this good to go, or do you have more commits coming?

**Comment by michihdeu** [comment]
No, this can go live now!

**Comment by yakra** [comment]
OK. I'll handle the changes to /devel/datacheck.php. Thanks for all your work on this!

**Comment by michihdeu** [comment]
Ah, I missed your previous post that you want to work on the remaining DL thing... Thanks! 😄

**Comment by michihdeu** [comment]
Or do you only wanna test my change to `devel_new` and copy to `devel`?

**Comment by yakra** [comment]
> Or do you only wanna test my change to `devel_new` and apply to `devel` if it's fine? Which would also be great!

This.

**Comment by jteresco** [comment]
This should be live on the main site now.

**Pull request merged**
