### PR TITLE
Fix blank tile option not showing up in systems.php

### PR DESCRIPTION
**Pull request by theFXexpert**
Can we not have the same js file located in three different places?

### CODE REVIEW

**Comment by jteresco** [comment]
Do you agree it should live only in the lib directory and any page that needs it should load from there?  If no objection, I'll make that happen.

**Comment by theFXexpert** [comment]
Yes. I'd prefer that.

**Comment by jteresco** [comment]
I merged in a little code from the various copies of chmviewerfunc3.js into the one /lib/tmjsfuncs.js file and updated the .php files to use that one.  I haven't noticed any errors from the change but haven't done anything close to thorough testing.

**Comment by yakra** [comment]
Last night, I did see the blank tile set show up briefly in system.php. It's gone again now. I've never seen it in region.php. May be useful there too.

**Comment by theFXexpert** [comment]
Blank tiles look good to me. But a divide by zero error occurs in mapview.php if devel systems are included (from #46). I'm not sure if it's because COALESCE() is not used on r.mileage in the SQL query or not.

**Pull request merged**
