### PR TITLE
center map at waypoint when clicking on table

### LINKED ISSUE #322: wpt editor: always center map option
Load a route and zoomed-in deep. Now, click on a line of the wp table on the left, and you'll get the wp displayed in the center of the map. If you click on a different line on the table, the wp is also displayed in the center again. However, if the 2nd wp is already displayed on the map - not center but anywhere else on the map - the map is not centered to that wp.

When I review a route, I click from wp to wp and check the position. It's quite annoying when the map is not centered and I need to move it manually so that I can see the name of the intersecting route et cetera. That happens when the wp is in the corner of the map view.

I don't know whether the current behavior is needed but I'd minimum like to be able to switch to the "always centered" option.

We do have the same behavior in HB. Maybe it's fine there as-is?

Thoughts?

### PR DESCRIPTION
**Pull request by yakra**
Fixes #322

### CODE REVIEW

**Comment by yakra** [comment]
Closing this pending some more testing on lab2

**Comment by yakra** [comment]
https://github.com/TravelMapping/Web/pull/361/commits/51b9b3097e98fc804424e1b936dc0f10c5dbb5db#diff-ee2abcb14108e77ec77a5cc1d194655dL841-R843 breaks centering for `Intersecting/Concurrent Routes` links, which are created before panning the map to the new center.
Alternately, 
```javascript
    markers[i].openPopup();
    map.panTo([lat, lon]);
    intersectingConcurrentRoutes(i);
```
introduces a new variant on the original problem: we `getCenter()` before the map is finished panning.

**Comment by yakra** [comment]
Fixed in a new commit.

**Comment by jteresco** [comment]
Live on tmtest.

**Comment by michihdeu** [comment]
It doesn't center and the opacity is 100%.

http://tmtest.teresco.org/wptedit/

**Comment by jteresco** [comment]
I'll hold off on putting this on the main site, then.

**Comment by yakra** [comment]
```
[yakra@noreaster /home/www/tmtest/wptedit]$ ls -l
total 48
-rw-r--r--  1 terescoj  wheel   4904 Jun 13  2018 index.php
-rw-r--r--  1 terescoj  wheel  40041 Jun 13  2018 wptfunctions.js
```

**Comment by yakra** [comment]
@michihdeu, how does the HB look re this?

**Comment by michihdeu** [comment]
?

I don't change the zoom level but just add a few wps next to each other, e.g.:

`+X847513 http://www.openstreetmap.org/?lat=42.719438&lon=-73.752058
+X225087 http://www.openstreetmap.org/?lat=42.719769&lon=-73.756821
+X907452 http://www.openstreetmap.org/?lat=42.719076&lon=-73.763430`

Then, click on the first wp of the table and it's **not** centered.

**Comment by jteresco** [comment]
Forgot that the wptedit code isn't updated by the default installer script.  Re-ran and the new code should be installed now.  Sorry about that.

**Comment by michihdeu** [comment]
Works fine! It's the most annoying issue with wpt editor. I think it can (and I hope it will) go live soon.

**Comment by jteresco** [comment]
Good!  @yakra agree it's safe to put all of this on the main site?

**Comment by yakra** [comment]
Yes, I think so.

**Comment by jteresco** [comment]
This and other changes from recently merged pull requests are live on the main site.

**Comment by yakra** [comment]
@FL0gnap, a simple Javascript fix for a big annoyance

**Pull request merged**
