### PR TITLE
Intersecting/Concurrent links keep same ctr/zoom

### PR DESCRIPTION
**Pull request by yakra**
Enhancement for #179.
A clean merge, despite all @jteresco's more recent work on some of these files. :D
Feature is live on my site mirror (link in the forum), so we can test it out & look for problems before merging.

### CODE REVIEW

**Comment by michihdeu** [comment]
👍 Thanks, that's really great 😍 I've tested it and it seems to work fine 😃 I think that the "Full Zoom" button (for switching back to "normal" mode) should be added before it goes live.

**Comment by michihdeu** [comment]
However, I hope that Jim's latest changes do not break anything nor your changes break anything of Jim's modifications. I recommend syncing both and test them on a non-production server before going live (I presume that we will see more implementations before that will happen though 😃).

**Comment by jteresco** [comment]
Sounds like the merge is already successfully done.  Just let me know when we're good to merge this one in and I'll get it on the tmtest server.

**Comment by yakra** [comment]
Lab2 has been updated with Jim's recent changes.

Full Zoom link also added.
I debated whether to only add it when the HB was set to a custom view (would it be clutter or potentially distracting otherwise...) but decided to keep it simple and Just Add It, in the regular HB too.
A lot of the time when I get an HB link to paste into the forum, I manually remove the user and unit parameters so as not to mess up the preferences of anyone following the link. This will make that process more simple; just right click, copy the link, and away we go.

Try it out; if it works well and we like what we see, I can add a commit to this pull request.

**Comment by jteresco** [comment]
I didn't know how much I wanted this enhancement until I tried it out.  I only poked around with it a bit, but it worked great everywhere I tried.  Minor suggestion: label the "Full Zoom" as "Zoom to Fit Route"  or something like that.  I think of "full zoom" as getting in as close as possible at the current location.

**Comment by yakra** [comment]
> Minor suggestion: label the "Full Zoom" as "Zoom to Fit Route" or something like that. I think of "full zoom" as getting in as close as possible at the current location.

Sounds good to me.

I prefer "Zoom to Fit", simply because it's less text. The current "Full Zoom" fits in a 1270px-wide Firefox window, but not 1269. We're starting to bump up against the limits of 1280xWhatever displays. I upgraded recently, but couldn't have been the last one on Earth... :)

Any objections?

**Comment by jteresco** [comment]
I like "Zoom to Fit".  Thanks.

We do want to keep tablets and even phones in mind when laying out our pages.

**Comment by yakra** [comment]
Hm. 1283px. ;P
"Fit Zoom?"
"View Related Routes?"

**Comment by jteresco** [comment]
I don't like "Fit Zoom" so much, but I'd even go for "Related Routes" without the "View".

**Comment by michihdeu** [comment]
"Zoom to Fit" is fine - name and feature 👍 
The name is much better than "Full zoom" since it can increase or decrease the zoom level.

**Comment by yakra** [comment]
I like keeping the "View" -- more clear name & feature.
Still fits in 1256 pixels.

**Comment by michihdeu** [comment]
> I'd even go for "Related Routes" without the "View".

Seconded! I think it's quite clear.

**Comment by yakra** [comment]
Two votes against, and I don't think anyone else is going to show up in this thread. :)
And it buys us a little more space.
Shall I go ahead & open the PR, then?

**Comment by michihdeu** [comment]
Go for it!

**Comment by jteresco** [comment]
Yes, let's get this in!

**Comment by michihdeu** [comment]
I think we should open a thread on the forum and explain the changes once the feature is live.

**Comment by jteresco** [comment]
This is on tmtest.teresco.org.  After the outage is over, I'll get it on the production site.  I just need to remember the corresponding changes to HDX code.

**Comment by yakra** [comment]
> I think we should open a thread on the forum and explain the changes once the feature is live.

http://forum.travelmapping.net/index.php?topic=3121

**Pull request merged**
