### PR TITLE
Highway System Colors -> System Colors

### PR DESCRIPTION
**Pull request by michihdeu**
@jteresco I don't know if there is a temporary copy of the source code for railways? If so, please apply the change. In the end of the day, we don't need to distinguish since System colors is good enough for any kind of transportation mode.

### CODE REVIEW

**Comment by jteresco** [comment]
Better to do what this PR does and make all modes say "System Colors" or have it be "Highway System Colors", "Railway System Colors", etc.?

**Comment by michihdeu** [comment]
> Better to do what this PR does and make all modes say "System Colors" or have it be "Highway System Colors", "Railway System Colors", etc.?

Generic System Color everywhere. Also for ski, ferry and whatsoever one day....

**Comment by jteresco** [comment]
Then I'll merge this in and install, thanks!

**Comment by michihdeu** [comment]
Thanks, can you also update the (hwy) production site?

**Pull request merged**
