### PR TITLE
graphs page bugfix

### PR DESCRIPTION
**Pull request by yakra**
http://forum.travelmapping.net/index.php?topic=3102

### CODE REVIEW

**Comment by jteresco** [comment]
Will pull this in after I merge in some stuff I've been playing with today on edge popups.  If it's not merged and live on site soon, remind me!

**Comment by yakra** [comment]
Many thanks. No worries if it's not on noreaster (which works fine) right away; it's live on lab2. :D

When you are on noreaster though, any chance you could [ingest an sql file](http://forum.travelmapping.net/index.php?topic=3102.msg14357#msg14357) to help attempt to recreate a bug with the `dbname` switch?

**Comment by jteresco** [comment]
Into TravelMappingTest?

**Comment by yakra** [comment]
Sure, TravelMappingTest works. Thanks!

**Pull request merged**
