### PR TITLE
LABEL_LOWERCASE & LOWERCASE_SUFFIX (Web)

### PR DESCRIPTION
**Pull request by yakra**
see https://github.com/TravelMapping/DataProcessing/pull/547

### CODE REVIEW

**Comment by michihdeu** [comment]
@yakra Thanks for implementing the feature 😄 I see both on datacheck.php and in the manual but I cannot manage to get an error in wpt editor. Does it work in wpt editor for you?

**Comment by yakra** [comment]
On lab2, yes.
[wptfunctions.js](https://github.com/TravelMapping/Web/commits/master/wptedit/wptfunctions.js) was last updated on noreaster on [Dec 27  2020](https://github.com/TravelMapping/Web/commit/58e9a979a6d9f29087da75be6492024ccbfcbfec).
@jteresco, it looks like you ran updateserver.sh without the `--wptedit` argument.

**Comment by jteresco** [comment]
You're right - running now with the correct arg.

**Comment by michihdeu** [comment]
Thanks, works to me now 😃

**Pull request merged**
