### PR TITLE
add canmbw, cansk

### PR DESCRIPTION
**Pull request by rschen7754**

### CODE REVIEW

**Comment by michihdeu** [comment]
shieldgen.php line 134 overwrites line the lines before.

$routeNum = str_replace("Rte", "", $row['route']);
-->
$routeNum = str_replace("Rte", "", $routeNum);

**Comment by rschen7754** [comment]
Good catch, fixed.

**Comment by jteresco** [comment]
Live on site.

**Comment by rschen7754** [comment]
Did both of the cansk files get uploaded? I'm not seeing them under cansph in the browser.

**Comment by rschen7754** [comment]
Never mind, found the bug and will submit a new pull request.

**Pull request merged**
