### PR TITLE
Favicons on webpages

### PR DESCRIPTION
**Pull request by theFXexpert**
Applies favicons to other pages.

### CODE REVIEW

**Comment by theFXexpert** [comment]
Just added a fix for some shields.

**Comment by jteresco** [comment]
This is live, looks like at least eure still coming up blank.

**Comment by theFXexpert** [comment]
Hmm. The code for the favicons isn't showing up either. There is also a superfluous semicolon in line 100 and line 134 of shieldgen.php

**Comment by jteresco** [comment]
I think I did not pull down the merged code before installing.  I did that now and I think things are a little better.

**Comment by theFXexpert** [comment]
Looks like the contents of line 111 in shieldgen.php: `$svg = str_replace("***NUMBER***", $routeNum, $svg);` should` be moved to after the next if block. 
$svg is getting overwritten with the wide shield template.

**Pull request merged**
