### PR TITLE
Additional Shields + A Little More

### PR DESCRIPTION
**Pull request by theFXexpert**
Shields added from Commons: 
- Guam
- canmbp Manitoba Provincial Roads #604 
- Northwest Territorial Highways #608 
- Texas Recreation Roads #596 

Winnipeg City Routes shield modified so the numbers don't look extremely bold.

Shieldgen function modified to handle usatxre
This case uses a regular expression to remove the prefix instead of relying on simple str_replaces on the region string etc.
This may help solve #121 ; I added cannt to this case to try it out.

### CODE REVIEW

**Comment by jteresco** [comment]
This is on tmstage to try it out.

**Comment by mapcat** [comment]
The shieldgen adjustment doesn't appear to be working on all routes:

https://tmstage.teresco.org/hb/showroute.php?u=mapcat&r=va.wv161bis
https://tmstage.teresco.org/hb/showroute.php?u=mapcat&r=ny.pa044cer

**Comment by theFXexpert** [comment]
It is not supposed to yet. Only for cannt.

**Comment by theFXexpert** [comment]
Anyway cannt and usatxre are definitely working as expected. I think this can be moved to prod.

**Comment by jteresco** [comment]
Live on the main site, thanks.

**Pull request merged**
