### PR TITLE
Header + LACKS_GENERIC

### PR DESCRIPTION
**Pull request by michihdeu**

### CODE REVIEW

**Comment by michihdeu** [comment]
@jteresco as requested [here](https://forum.travelmapping.net/index.php?topic=3172.msg19374#msg19374)

Not sure about the text, but "Participate" would sound odd. I'm gone with CHM wording but you can rename it if you think it should be renamed.

**Comment by yakra** [comment]
Looks fine to me.
@michihdeu, ready to merge in?

**Comment by michihdeu** [comment]
yep, ready for take-off! 🛩️ but @jteresco must bring it live....

**Comment by jteresco** [comment]
And it's live on the main site.

**Pull request merged**
